import { useRouter } from "next/router";
import styles from "../../styles/delDoc.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useState, useEffect } from "react";
import { Spinner } from "reactstrap";

export default function DelDoc() {
  const [loading, setLoading] = useState(false);
  const [disable, setDisable] = useState(false);
  const [docs, setDocs] = useState([]);
  const [doc, setDoc] = useState([]);
  const router = useRouter();
  const { doc_id } = router.query;

  const deleteDoc = async () => {
    setDisable(true);
    const req = await fetch(`/api/docs/delDoc/${doc_id}`, {
      method: "DELETE",
      headers: {
        "Content-Type": "application/json",
      },
    });
    const res = await req.json();
    if (res.success) {
      router.push("/docs");
    } else {
      alert("Can't delete the document");
    }
  };

  useEffect(() => {
    const load = async () => {
      const res = await fetch("/api/docs/docs");
      const data = await res.json();
      setDocs(data);
      setLoading(true);
    };

    const loadDoc = () => {
      for (let i = 0; docs.length; i++) {
        if (docs[i]._id === doc_id) {
          setDoc(docs[i]);
          break;
        }
      }
    };
    load();
    loadDoc();
  }, [loading]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Gestion Documental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Link className={styles.Link} href="/">
          <h3>Gestion Documental</h3>
        </Link>
        <div className={styles.header}>
          <Link className={styles.Link} href="/docs">
            Docs
          </Link>
          <Link className={styles.Link} href="/category">
            Categories
          </Link>
          <Link className={styles.Link} href="/inventory">
            Inventory
          </Link>
        </div>
      </header>

      <main className={styles.main}>
        {loading ? (
          <>
            <h1 className={styles.title}>Delete Document</h1>
            <p>
              Are you sure you want to delete <span>{`"${doc.Titulo}"`}</span>?
            </p>
            <div hidden={disable}>
              <button onClick={deleteDoc} className={styles.deleteBtn}>
                Delete
              </button>
              <Link href={"/docs"} className={styles.cancelBtn}>
                Cancel
              </Link>
            </div>
            <Spinner hidden={!disable} />
          </>
        ) : (
          <Spinner hidden={loading} />
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
