import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gestion Documental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Link className={styles.Link} href="/">
          <h3>Gestion Documental</h3>
        </Link>
        <div className={styles.header}>
          <Link className={styles.Link} href="/docs">
            Docs
          </Link>
          <Link className={styles.Link} href="/category">
            Categories
          </Link>
          <Link className={styles.Link} href="/inventory">
            Inventory
          </Link>
        </div>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a <a>Gestion Documental!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
